FROM node:22-alpine

WORKDIR /app

COPY server/package*.json ./
COPY server/jest.config.ts ./
COPY server/jest.setup.ts ./
COPY server/tsconfig.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "test"]